name: auto_quote_generator_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  share_plus: ^10.0.2
  flutter_animated_button: ^2.0.3
  google_fonts: ^6.2.1
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/lottie.json
    - assets/images/logo.png
    - assets/images/motivation.jpeg
    - assets/images/love.jpg
    - assets/images/philosphy.jpg
    - assets/images/birthday.jpg
    - assets/images/friends.jpg
    - assets/images/life.jpg
    - assets/images/wisdom.jpg
